package cn.qatime.teacher.player.bean;

public enum BusEvent {
    PAY_SUCCESS,
    REFRESH_CASH_ACCOUNT,
    ON_REFRESH_CASH_ACCOUNT,
    HANDLE_U_PUSH_MESSAGE,
    ANNOUNCEMENT,
    PAY_PASSWORD_CHANGE,
    REFRESH_NOTIFICATIONS
}
